### PR TITLE
cmd/search/main: Pull artifacts straight from Google

### PR DESCRIPTION
**Pull request by wking**
Builds on #16; review that first.

This is faster and more reliable than pulling them from Deck, which was giving me lots of:

```
Unable to retrieve container logs for docker://...
```

errors.  It also sets the stage for optionally pulling additional artifacts (`events.json`, etc.).

### CODE REVIEW

**Comment by smarterclayton** [comment]
If gcs upload fails, we won't have them on GCS.  But I could maybe buy this in terms of overall simplicity.

**Comment by smarterclayton** [comment]
For instance an evicted pod may still have logs but not succeed at reporting to GCS.  If you can verify that *isn't* the case, this should be totally safe to merge.

**Comment by wking** [comment]
I see lots of `Unable to retrieve container logs for docker://...` errors without this patch, and I have yet to notice errors with this patch.  So already demonstrably higher success, even if this patch isn't 100% successful (and while I don't have any known failures from this approach to report, nothing is 100% successful ;).  To see these errors in the production deployment, visit https://search.svc.ci.openshift.org/?search=Unable+to+retrieve+container+logs+for+docker&maxAge=168h&context=2&type=all

**Comment by wking** [comment]
> ... and while I don't have any known failures from this approach...

Ah, here's one.  [this scaleupdown periodic][1] links its `build-log.txt` to [the `/log` endpoint][2] and [has no [GCS version][3].  I'm not sure if that's specific to periodics, `periodic-ci-azure-e2e-scaleupdown-v4.2`, or that specific failure mode:

```json
{
  "component": "entrypoint",
  "error": "could not start the process: fork/exec hack/tests/e2e-scaleupdown-previous.sh: no such file or directory",
  "level": "error",
  "msg": "Error executing test process",
  "time": "2019-04-29T20:25:35Z"
}
```

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/periodic-ci-azure-e2e-scaleupdown-v4.2/7
[2]: https://deck-ci.svc.ci.openshift.org/log?job=periodic-ci-azure-e2e-scaleupdown-v4.2&id=7
[3]: https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-scaleupdown-v4.2/7

**Comment by wking** [comment]
Ok, I've rerolled this with b64357f -> bbfbb85 to pull from Google and fall back to Prow if Google fails.  Although it looks like I need to rebase again ;).

**Comment by wking** [comment]
Rebased around #20 with bbfbb85 -> b93eee9.

**Comment by wking** [comment]
Landed via #24.

**Pull request closed without merging**
